import json
from pathlib import Path

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from langchain_ollama import OllamaLLM


# ============================================================
# RISK ASSESSMENT AGENT
# ============================================================

app = FastAPI(
    title="Risk Assessment Agent",
    description="A2A risk assessment agent",
)


# ============================================================
# PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

AUDIT_DIR = (
    BASE_DIR
    / "audit_report"
)

CODE_AUDIT_REPORT = (
    AUDIT_DIR
    / "code_audit.json"
)

RISK_ASSESSMENT_REPORT = (
    AUDIT_DIR
    / "risk_assessment_report.json"
)


# ============================================================
# LLM
# ============================================================

llm = OllamaLLM(
    model="llama3.2"
)


# ============================================================
# REQUEST MODEL
# ============================================================

class Task(BaseModel):
    task: str


# ============================================================
# LOAD CODE AUDIT
# ============================================================

def load_code_audit():

    if not CODE_AUDIT_REPORT.exists():

        raise FileNotFoundError(
            f"Code audit report not found: "
            f"{CODE_AUDIT_REPORT}"
        )

    with open(
        CODE_AUDIT_REPORT,
        "r",
        encoding="utf-8"
    ) as f:

        return json.load(f)


# ============================================================
# SAVE RISK ASSESSMENT
# ============================================================

def save_risk_assessment(
    assessment
):

    AUDIT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        RISK_ASSESSMENT_REPORT,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            assessment,
            f,
            indent=4
        )


# ============================================================
# RISK ASSESSMENT
# ============================================================

def perform_risk_assessment(
    task: str
):

    # --------------------------------------------------------
    # Load report generated by Code Review Agent
    # --------------------------------------------------------

    audit = load_code_audit()

    audit_json = json.dumps(
        audit,
        indent=4
    )

    # --------------------------------------------------------
    # Risk assessment prompt
    # --------------------------------------------------------

    prompt = f"""
You are a security risk assessment agent.

Another security agent has already performed a code review.

Your task is to assess the overall security risk of the
application based ONLY on the supplied code-review report.

Do not invent vulnerabilities.

Do not modify or add vulnerabilities to the original findings.

Assess:

- Overall security risk
- Business impact
- Exploitability
- Potential consequences
- Risk prioritization
- Recommended remediation priority
- Production readiness

Return ONLY valid JSON.

Use exactly this structure:

{{
    "application": "vulnerable_app",
    "overall_risk": "CRITICAL|HIGH|MEDIUM|LOW",
    "production_ready": true,
    "risk_assessment": {{
        "business_impact": "string",
        "exploitability": "string",
        "potential_consequences": "string",
        "priority": "string"
    }},
    "prioritized_findings": [
        {{
            "id": "CR-001",
            "severity": "CRITICAL|HIGH|MEDIUM|LOW",
            "priority": 1,
            "reason": "string",
            "recommended_action": "string"
        }}
    ],
    "executive_summary": "string"
}}

The original code-review report is:

---------------- BEGIN CODE AUDIT ----------------

{audit_json}

----------------- END CODE AUDIT -------------------

User task:

{task}
"""

    # --------------------------------------------------------
    # Run local LLM
    # --------------------------------------------------------

    response = llm.invoke(
        prompt
    )

    response = response.strip()

    # --------------------------------------------------------
    # Remove Markdown JSON fences
    # --------------------------------------------------------

    if response.startswith("```"):

        lines = response.splitlines()

        if lines:

            lines = lines[1:]

        if (
            lines
            and lines[-1].strip() == "```"
        ):

            lines = lines[:-1]

        response = "\n".join(
            lines
        ).strip()

    # --------------------------------------------------------
    # Parse JSON
    # --------------------------------------------------------

    try:

        assessment = json.loads(
            response
        )

    except json.JSONDecodeError:

        start = response.find("{")
        end = response.rfind("}")

        if start == -1 or end == -1:

            raise ValueError(
                "Risk Assessment Agent did not "
                "return valid JSON."
            )

        try:

            assessment = json.loads(
                response[
                    start:end + 1
                ]
            )

        except json.JSONDecodeError as ex:

            raise ValueError(
                f"Unable to parse risk assessment: {ex}"
            )

    # --------------------------------------------------------
    # Add metadata
    # --------------------------------------------------------

    assessment["agent"] = (
        "risk-assessment-agent"
    )

    assessment["source_report"] = str(
        CODE_AUDIT_REPORT
    )

    assessment["output_report"] = str(
        RISK_ASSESSMENT_REPORT
    )

    # --------------------------------------------------------
    # Save report
    # --------------------------------------------------------

    save_risk_assessment(
        assessment
    )

    return assessment


# ============================================================
# A2A TASK ENDPOINT
# ============================================================

@app.post("/a2a/task")
def process_task(
    task: Task
):

    try:

        assessment = perform_risk_assessment(
            task.task
        )

        return {
            "agent": "risk-assessment-agent",
            "type": "risk_assessment_result",
            "status": "completed",
            "task": task.task,
            "report_file": str(
                RISK_ASSESSMENT_REPORT
            ),
            "assessment": assessment,
        }

    except Exception as ex:

        raise HTTPException(
            status_code=500,
            detail=str(ex)
        )


# ============================================================
# MANUAL ASSESSMENT ENDPOINT
# ============================================================

@app.post("/assess")
def run_assessment():

    try:

        assessment = perform_risk_assessment(
            "Assess the security risk of the application."
        )

        return {
            "status": "completed",
            "report_file": str(
                RISK_ASSESSMENT_REPORT
            ),
            "assessment": assessment,
        }

    except Exception as ex:

        raise HTTPException(
            status_code=500,
            detail=str(ex)
        )


# ============================================================
# HEALTH CHECK
# ============================================================

@app.get("/health")
def health_check():

    return {
        "agent": "risk-assessment-agent",
        "status": "healthy",
        "model": "llama3.2",
        "code_audit_report": str(
            CODE_AUDIT_REPORT
        ),
        "risk_assessment_report": str(
            RISK_ASSESSMENT_REPORT
        ),
        "code_audit_exists": (
            CODE_AUDIT_REPORT.exists()
        ),
        "risk_assessment_exists": (
            RISK_ASSESSMENT_REPORT.exists()
        ),
    }